# WELCOME TO TECHNICAL TRAININGS

## NUMPY LIBRARY DISCUSION 

## What is NumPy?
NumPy is a python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

## Why Use NumPy ?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster that traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important

### Installation of NumPy
If you have Python and PIP already installed on a system, then installation of NumPy is very easy.

Install it using this command:



In [3]:
#C:\Users\Your Name>pip install numpy

In [1]:
import numpy

In [3]:
import numpy

arr = numpy.array([1,"LIKE", 2, 3, 4, 5])

print(arr)

['1' 'LIKE' '2' '3' '4' '5']


In [5]:
import numpy as np                                #Alias- alternate name for same thing

arr = np.array([1, "SUBSCRIBE","share", 3, 4, 5])

print(arr)

['1' 'SUBSCRIBE' 'share' '3' '4' '5']


In [6]:
np.__version__                                 #version

'1.16.5'

In [7]:
#dimensions of array 

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
import numpy as np                              #indexing

arr = np.array([1, 2, 3, 4])

print(arr[3])

4


## Shape of an Array
The shape of an array is the number of elements in each dimension.

In [12]:
import numpy as np

arr = np.array([[[1, 2, 3, 4],[1, 2, 3, 4], [5, 6, 7, 8]]])

print(arr.shape)

(1, 3, 4)


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4,5,6,7,8,9,0], ndmin=4)

print(arr)
print('shape of array :', arr.shape)

[[[[1 2 3 4 5 6 7 8 9 0]]]]
shape of array : (1, 1, 1, 10)


## Reshaping the array

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(6, 2)

print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


## Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.

In [20]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


## Splitting NumPy Arrays
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits

In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 5)                                #OPPOSITE OF JOINING

print(newarr)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


# Numpy | Indexing
NumPy or Numeric Python is a package for computation on homogenous n-dimensional arrays. In numpy dimensions are called as axes.

In [24]:
import numpy as np
 
list1 = [7,6,5,8,5,6,3,6,3]
list2 = [1,4,2,5,6,6,4,4,4]
 
a1 = np.array(list1)
a2 = np.array(list2)
 
print(a1*a2)                                               #normal operation is not possible 

[ 7 24 10 40 30 36 12 24 12]


## INDEXING 

In [27]:
import numpy as np
 
# Arrange elements from 0 to 19
a = np.arange(30)
print(a)

# The : operator means all elements till the end.
print("\n",a[0:11])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

 [ 0  1  2  3  4  5  6  7  8  9 10]


In [29]:
import numpy as np
 
a = np.array([10, 40, 80, 50.+])
print(a[a>50])

[ 80 100]
